# Generated by Django 4.2.2 on 2023-07-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mondev_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mondev_site.page')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('lt', 'Lietuvių')], db_index=True, max_length=7, verbose_name='language')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mondev_site.page', verbose_name='page')),
            ],
            options={
                'abstract': False,
            },
            bases=('mondev_site.page',),
        ),
    ]
