SECRET_KEY=''
POSTGRES_DB='monda'
POSTGRES_USER='monda'
POSTGRES_PASSWORD=''
POSTGRES_PORT=5432
POSTGRES_HOST='postgres'
EMAIL_ID='yourmail@gmail.com'
EMAIL_PW='googlesecretkey'
DEFAULT_FROM_EMAIL = 'defaultnoreply@email.com'