# Generated by Django 4.2.2 on 2023-07-03 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0002_alter_coursetopic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63, verbose_name='name')),
                ('code', models.SlugField(max_length=7, unique=True, verbose_name='short name')),
                ('starting_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='starting date')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'course group',
                'verbose_name_plural': 'course groups',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, max_length=7, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='TopicMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, max_length=127, null=True, upload_to='academy/topic_material/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'topic material',
                'verbose_name_plural': 'topic materials',
            },
        ),
        migrations.CreateModel(
            name='CourseGroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academy.coursegroup', verbose_name='course group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'course group student',
                'verbose_name_plural': 'course group students',
                'ordering': ('course_group', 'user'),
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academy.course', verbose_name='course'),
        ),
    ]
