# Generated by Django 4.2.2 on 2023-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_rename_coursegroupstudent_coursegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmember',
            name='is_assistant',
            field=models.BooleanField(default=False, verbose_name='assistant'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name='expert'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='is_lecturer',
            field=models.BooleanField(default=False, verbose_name='lecturer'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='recruiter'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='student'),
        ),
    ]
