# Generated by Django 4.2.2 on 2023-07-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_coursegroupmember_is_assistant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroupmember',
            options={'ordering': ('course_group', 'user'), 'verbose_name': 'course group member', 'verbose_name_plural': 'course group members'},
        ),
        migrations.AlterModelOptions(
            name='topicmaterial',
            options={'ordering': ('order',), 'verbose_name': 'topic material', 'verbose_name_plural': 'topic materials'},
        ),
    ]
