# Generated by Django 4.2.2 on 2023-07-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_coursegroupmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTranslation',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academy.topic')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('lt', 'Lietuvių')], db_index=True, max_length=7, verbose_name='language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='academy.topic', verbose_name='topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('academy.topic', models.Model),
        ),
        migrations.CreateModel(
            name='TopicMaterialTranslation',
            fields=[
                ('topicmaterial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academy.topicmaterial')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('lt', 'Lietuvių')], db_index=True, max_length=7, verbose_name='language')),
                ('topic_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabslations', to='academy.topicmaterial', verbose_name='topic material')),
            ],
            options={
                'abstract': False,
            },
            bases=('academy.topicmaterial', models.Model),
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academy.course')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('lt', 'Lietuvių')], db_index=True, max_length=7, verbose_name='language')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='academy.course', verbose_name='course')),
            ],
            options={
                'abstract': False,
            },
            bases=('academy.course', models.Model),
        ),
    ]
