# Generated by Django 4.2.2 on 2023-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_topictranslation_topicmaterialtranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='graduation_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='graduation date'),
        ),
    ]
