# Generated by Django 4.2.2 on 2023-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_coursegroup_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='days per week'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='hours_per_day',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='hours per day'),
        ),
    ]
