# Generated by Django 4.2.2 on 2023-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_coursegroup_days_per_week_coursegroup_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmember',
            name='contract_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='contract accepted at'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='contract_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='contract url'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='payment_method',
            field=models.CharField(choices=[('pre_kevin', 'Prepaid Kevin'), ('pre_stripe', 'Prepaid Stripe'), ('plan_kevin', 'Payment Plan'), ('sponsored', 'Sponsored Scholarship')], default='pre_kevin', max_length=15, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='coursegroupmember',
            name='scholarship_sponsor',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='scholarship sponsor'),
        ),
    ]
