# Generated by Django 4.2.2 on 2023-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_remove_coursegroupmember_contract_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmember',
            name='background',
            field=models.TextField(blank=True, null=True, verbose_name='background'),
        ),
    ]
