# Generated by Django 4.2.2 on 2023-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_coursegroupmember_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmember',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('rejected', 'Rejected')], default='new', max_length=15, verbose_name='status'),
        ),
    ]
