# Generated by Django 4.2.2 on 2023-07-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_coursegroupmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroupmember',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group_members', to='academy.coursegroup', verbose_name='course group'),
        ),
    ]
