# Generated by Django 4.2.2 on 2023-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_alter_coursegroupmember_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmember',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
