# Generated by Django 4.2.2 on 2023-08-04 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_coursegroupsession_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroupsession',
            name='name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at'),
        ),
    ]
