# Generated by Django 4.2.2 on 2023-08-09 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_remove_coursegroupsession_name_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check in'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check out'),
        ),
        migrations.AlterField(
            model_name='coursegroupsession',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='academy.coursetopic', verbose_name='course topic'),
        ),
        migrations.AlterField(
            model_name='coursegroupsession',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
