# Generated by Django 4.2.2 on 2023-08-02 10:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_template_text', tinymce.models.HTMLField(verbose_name='contract template text')),
            ],
            options={
                'verbose_name': 'contract template',
                'verbose_name_plural': 'contracts templates',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='contract_app.contracttemplate', verbose_name='Contract template'),
        ),
    ]
