# Generated by Django 4.2.2 on 2023-08-02 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_app', '0002_contracttemplate_contract_contract_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contract_app.contract', verbose_name='contract')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signator', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
